

OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: unir.com
    CA:
        Country: ES
        Province: Madrid
        Locality: Madrid
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
    
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: org1
    Domain: org1.unir.com
    EnableNodeOUs: true
    CA:
      Country: ES
      Province: Madrid
      Locality: Madrid
    Template:
      Count: 1
    Users:
      Count: 1
 
  - Name: org2
    Domain: org2.unir.com
    EnableNodeOUs: true
    CA:
        Country: ES
        Province: Madrid
        Locality: Madrid
    Template:
      Count: 1
    Users:
      Count: 1
    